version: '3'

services:
  proxy:
    image: nginx:latest
    container_name: proxy
    restart: unless-stopped
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    restart: unless-stopped
    expose:
      - "80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
